apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    name: ""
    namespace: ingress
    server: "https://kubernetes.default.svc"
  source:
    path: charts/nginx
    repoURL: "git@github.com:hamishfor/helm-charts.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
