apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    name: ""
    namespace: ingress
    server: "https://kubernetes.default.svc"
  source:
    path: .
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.10.1"
    helm:
      valueFiles:
        - $values/charts/nginx/values.yaml
  sources:
    - repoURL: "git@github.com:hamishfor/helm-values.git"
      targetRevision: HEAD
      ref: values
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: "4.10.1"
      helm:
        valueFiles:
          - $values/charts/nginx/values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
