---
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "deluge.harcodedValues" -}}

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    enabled: true
    ports:
      web:
        enabled: true
        port: 8112
        protocol: TCP
        targetPort: 8112
      daemon:
        enabled: true
        port: 58846
        protocol: TCP
        targetPort: 58846


{{- end -}}
{{- $_ := mergeOverwrite .Values (include "deluge.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}

{{ include "common.all" . }}