---
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "deluge.harcodedValues" -}}

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    ports:
      https:
        port: 8112

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "deluge.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}

{{ include "common.all" . }}