project: default
source:
  repoURL: "git@github.com:hamishfor/helm-charts.git"
  path: charts/deluge
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: service.main.ports.http.enabled
        value: "true"
destination:
  server: "https://kubernetes.default.svc"
  namespace: deluge
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
