#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: linuxserver/deluge
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 2.1.1-r8-ls262

# -- environment variables. See more environment variables in the [deluge documentation](https://github.com/linuxserver/docker-deluge#parameters).
# @default -- See below
env:
  # -- Specify the user ID the application will run as
  PUID: "1000"
  # -- Specify the group ID the application will run as
  PGID: "1000"
  # -- Set the container timezone
  TZ: "Pacific/Auckland"
  # -- Set the loglevel output when running Deluge
  DELUGE_LOGLEVEL: "info"

# -- Configures service settings for the chart.
# @default -- See values.yaml

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /lake/data/config/deluge/
    accessMode: ReadWriteMany
    mountPath: /config

  downloads:
    enabled: true
    type: hostPath
    hostPath: /lake/media
    accessMode: ReadWriteMany
    mountPath: /lake/media

ingress:
  main:
    # -- Enables or disables the ingress
    enabled: true

    # -- Make this the primary ingress (used in probes, notes, etc...).
    # If there is more than 1 ingress, make sure that only 1 ingress is marked as primary.
    primary: true

    # -- Override the name suffix that is used for this ingress.
    nameOverride:

    # -- Provide additional annotations which may be required.
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      kubernetes.io/tls-acme: "true"
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    # -- Provide additional labels which may be required.
    labels: {}

    # -- Set the ingressClass that is used for this ingress.
    # Requires Kubernetes >=1.19
    ingressClassName: nginx

    ## Configure the hosts for the ingress
    hosts:
      - # -- Host address. Helm template can be passed.
        host: deluge.hamishandholly.com
        ## Configure the paths for the host
        paths:
          - # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
    tls:
      - secretName: deluge-tls
        hosts:
          - deluge.hamishandholly.com

service:
  main:
    ports:
      http:
        enabled: false
