#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

global:
  annotations:
    - flame.pawelmalak/type=application # "app" works too
    - flame.pawelmalak/name=Flame
    - flame.pawelmalak/url=https://flame.example.com
    - flame.pawelmalak/icon=kubernetes # optional, default is "kubernetes"

image:
  # -- image repository
  repository: pawelmalak/flame
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 2.3.1

# -- environment variables. See more environment variables in the [deluge documentation](https://github.com/pawelmalak/flame/wiki).
# @default -- See below
env:
  # -- Specify the user ID the application will run as
  PUID: "1000"
  # -- Specify the group ID the application will run as
  PGID: "1000"
  # -- Set the container timezone
  TZ: "Europe/London"
  PASSWORD: password

# -- Configures service settings for the chart.
# @default -- See values.yaml

service:
  main:
    ports:
      http:
        enabled: true
        protocol: HTTP
        port: 80
      https:
        enabled: true
        protocol: TCP
        port: 443

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /config
