apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: bitwarden
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bitwarden
    server: {{ .Values.spec.destination.server }}
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: {{ .Values.spec.source.ref }}
    - repoURL: https://charts.bitwarden.com
      targetRevision: "self-host-2024.7.2"
      chart: bitwarden
      helm:
        valueFiles:
          - $values_repo/charts/bitwarden/values.yml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
