apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: immich
    server: {{ .Values.spec.destination.server }}
  source:
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: {{ .Values.spec.source.ref }}
    - repoURL: https://hamishfor.github.io/helm-charts
      targetRevision: "0.1.6"
      chart: immich
      helm:
        valueFiles:
          - $values_repo/charts/immich/values.yml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
