apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nzbget
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nzbget
    server: {{ .Values.spec.destination.server }}
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: {{ .Values.spec.source.ref }}
    - repoURL: https://geek-cookbook.github.io/charts/
      targetRevision: "12.4.2"
      chart: nzbget
      helm:
        valueFiles:
          - $Values/charts/nzbget/values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
