apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pihole
    server: {{ .Values.spec.destination.server }}
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: {{ .Values.spec.source.ref }}
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: "2.27.0"
      chart: pihole
      helm:
        valueFiles:
          - $values_repo/charts/pihole/values.yml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
