apiVersion: v2
name: local-path-provisioner
description: Wrapper chart for local-path-provisioner with custom configurations
type: application
version: 0.1.0
appVersion: "v0.0.32"

dependencies:
  - name: local-path-provisioner
    repository: file://local-path-provisioner-0.0.32.tgz
    version: "0.0.32"