apiVersion: v2
name: supabase
description: The open source Firebase alternative.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# Not used because too difficult to follow correctly
# appVersion: "1.16.0"

# A URL to an SVG or PNG image to be used as an icon
icon: https://avatars.githubusercontent.com/u/54469796?s=280&v=4
annotations:
  artifacthub.io/changes: >2
     - "all values->Values ([3c63014](https://github.com/hamishfor/helm-charts/commit/3c63014ac6b61b038f934ea1cdc80b756a5a58b9))"
     - "app-of-apps create namespace ([a0e0d38](https://github.com/hamishfor/helm-charts/commit/a0e0d38c54756a915ff7f36f2e9398a54a4b0f19))"
     - "deluge indenting ([67706d2](https://github.com/hamishfor/helm-charts/commit/67706d2806425a907a69b02e7d0eae0816daa384))"
     - "deluge values.yaml path ([d2d12f1](https://github.com/hamishfor/helm-charts/commit/d2d12f1214fb2fabd548df39fec3511174223925))"
     - "docker-registry chart version ([6c268fe](https://github.com/hamishfor/helm-charts/commit/6c268fe5cd637999756917f46ba9d2c6e1209669))"
     - "docker-registry values->Values ([5345bfe](https://github.com/hamishfor/helm-charts/commit/5345bfebf921de1021479f8afbe8e8beaca3b494))"
     - "ghtoken ([66ba73f](https://github.com/hamishfor/helm-charts/commit/66ba73f8eeeaf76b8a6efbbd0695934bf334906a))"
     - "hardcoded values template ([ce58599](https://github.com/hamishfor/helm-charts/commit/ce58599860e2cf276d26994cf5fe036aee6a4f3c))"
     - "improper constraint \"app-x.x.x\" ([e73f9d2](https://github.com/hamishfor/helm-charts/commit/e73f9d28823e585b69b84bc43e18138bc8dfb987))"
     - "nginx destination naem ([f518cb9](https://github.com/hamishfor/helm-charts/commit/f518cb9a183dbf9f63f59988f0d3359814b2eb5a))"
     - "nzbget version ([f2c05b4](https://github.com/hamishfor/helm-charts/commit/f2c05b4e83b2a47cee10a9150efc2f2e342c430e))"
     - "prometheus version ([5499a11](https://github.com/hamishfor/helm-charts/commit/5499a115d895879987de798b9867a6bab8f6bd4d))"
     - "prunelast=true ([83fccc2](https://github.com/hamishfor/helm-charts/commit/83fccc2c9ffff6977077c0e62aaeee93156ad534))"
     - "update prometheus to correct chart version ([3d70dd3](https://github.com/hamishfor/helm-charts/commit/3d70dd3e04123582fbf5079d9cc0301bfe3e6796))"
     - "values reference var ([719e9b2](https://github.com/hamishfor/helm-charts/commit/719e9b21e04b9d33ff26f9c61d9ef0c25c749d66))"
     - "values repo revision ([1b49259](https://github.com/hamishfor/helm-charts/commit/1b492595280bc339815c9c35961bf01b505f9c17))"
     - "values.yaml -> values.yml ([15877d2](https://github.com/hamishfor/helm-charts/commit/15877d2572d16b33f1f9feca5b2e6ac12c72dd8b))"
     - "web = http ([158f8c3](https://github.com/hamishfor/helm-charts/commit/158f8c31b3f3ecbaaa7ab2fd54e8432b0d352259))"
     - "-flame ([b9aa965](https://github.com/hamishfor/helm-charts/commit/b9aa965db0d8bd57bdda2446cd4de1639422fbe1))"
     - "1.5.0 ([0a80106](https://github.com/hamishfor/helm-charts/commit/0a8010630c3a9b85a1411fba09cc12bcbd9fea24))"
     - "actions CR_TOKEN ([9cbc713](https://github.com/hamishfor/helm-charts/commit/9cbc713d814f67f95f72901a3540ecc8eb1d9df8))"
     - "bitwarden ([831edc7](https://github.com/hamishfor/helm-charts/commit/831edc7c4eccbb541a921b2e3327aef78ac9aace))"
     - "deluge -name ([a42b0b9](https://github.com/hamishfor/helm-charts/commit/a42b0b90a55bb0abc1d704babbab8fd7eef227f3))"
     - "docker-registry ([1e28ef1](https://github.com/hamishfor/helm-charts/commit/1e28ef15811fc14d7aa272cdf72bc14c371317e9))"
     - "flame ([58d6842](https://github.com/hamishfor/helm-charts/commit/58d6842c908bef49f798e3e0179bc76f766e6e42))"
     - "nzbget ([6408f59](https://github.com/hamishfor/helm-charts/commit/6408f5999b6b5618dc7ddb6b2c593c2f48a3eaa2))"
     - "plex ([aeee8d6](https://github.com/hamishfor/helm-charts/commit/aeee8d6077fdb7b37fc1739b9ef4b964d7823ba0))"
     - "prometheus ([89061d7](https://github.com/hamishfor/helm-charts/commit/89061d7a78328898a86ad8b4db6f0a26979fccb2))"
     - "radarr -name ([2b1ad92](https://github.com/hamishfor/helm-charts/commit/2b1ad92f0e2b3936beccabb9e0d0724bfc861bc0))"
     - "sonarr ([210cb08](https://github.com/hamishfor/helm-charts/commit/210cb08ae735217a1fbd09dcc988a32a562dc580))"
     - "sonarr -name ([c97f447](https://github.com/hamishfor/helm-charts/commit/c97f44740929e03c315f3ff9526b312f0c5a94cb))"
     - "supabase ([ecd7dc3](https://github.com/hamishfor/helm-charts/commit/ecd7dc3a76e1ea973dd2d61ef7a63b910606f12b))"
     - "upgrade flame ([cafe9a4](https://github.com/hamishfor/helm-charts/commit/cafe9a490735df02f158df71de968003a68d0505))"
