# name: Release Charts

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main


# jobs:
#   release:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
#         with:
#           fetch-depth: 0

#       - name: Configure Git
#         run: |
#           git config user.name "$GITHUB_ACTOR"
#           git config user.email "$GITHUB_ACTOR@gmail.com"

#       - name: Install Helm
#         uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
#         with:
#           version: v3.14.3 # renovate: datasource=github-releases depName=helm packageName=helm/helm

#       - name: Add repositories
#         run: |
#           for dir in $(ls -d charts/*/); do
#             helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
#           done

#       - name: Build chart dependencies
#         run: |
#           for dir in charts/*/
#           do
#               (cd ${dir}; helm dependency build)
#           done

#       - name: Run chart-releaser
#         uses: helm/chart-releaser-action@v1.7.0 # v1.7.0
#         with:
#           config: .github/cr.yaml
#           packages_with_index: true
#           pages_branch: gh-pages
#           charts_dir: charts
#         env:
#           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#           CR_GENERATE_RELEASE_NOTES: true
#           CR_SKIP_EXISTING: false
